default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wacdo
  password: MmsbQMznMCZWkX8uthyz8wVnjXpFh2ZM
  host: dpg-d0o2b0uuk2gs73fkrolg-a.oregon-postgres.render.com
  port: 5432
  database: wacdo_w9gw

development:
  <<: *default

test:
  <<: *default
  database: notebook_test

production:
  <<: *default