default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wacdo
  password: MmsbQMznMCZWkX8uthyz8wVnjXpFh2ZM
  host: dpg-d0o2b0uuk2gs73fkrolg-a.oregon-postgres.render.com
  port: 5432

production:
  primary:
    <<: *default
    database: wacdo_w9gw
  cable:
    <<: *default
    database: wacdo_w9gw  # Ou une DB dédiée au cable si tu en as une

development:
  primary:
    <<: *default
    database: wacdo_w9gw_dev
  cable:
    <<: *default
    database: wacdo_w9gw_dev

test:
  primary:
    <<: *default
    database: wacdo_test
  cable:
    <<: *default
    database: wacdo_test
